{% set name = "qimage2ndarray" %}
{% set version = "1.8.2" %}
{% set sha256 = "0f792693a0f1cd5f93fbf73bc3fb2d511fb9cceed3c9308bfb200f38c19a5545" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  requires:
    - pyqt 5*

  imports:
    # Need to import Python-bindings first
    # so that qimage2ndarray recognizes them.
    - PyQt5
    - qimage2ndarray

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: BSD 3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  # Requested the license file be packaged upstream.
  #
  # https://github.com/hmeine/qimage2ndarray/pull/10
  #
  #license_file: LICENSE.txt
  summary: Conversion between QImages and numpy.ndarrays.
  description: |
    qimage2ndarray is a small python extension for quickly converting
    between ``QImages`` and ``numpy.ndarrays`` (in both directions).
  doc_url: http://hmeine.github.io/qimage2ndarray
  dev_url: https://github.com/hmeine/qimage2ndarray

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
